[package]
name = "xinyu-app"
version = "0.1.1"
description = "心愈 · 心理健康服务平台桌面端"
authors = ["you"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-notification = "2"
tauri-plugin-global-shortcut = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
aes-gcm = "0.10"
base64 = "0.22"
# 检查更新：HTTP 请求（Gitee Releases API）
reqwest = { version = "0.12", default-features = false, features = ["blocking", "json", "rustls-tls"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
